### ISSUE TITLE
missing the module LoG.dataset.overlook

### ISSUE THREAD

**Issue by lys5588** [zju3dv/LoG#12]
Hi, I'm using the urbanBiS dataset to run the training program using the given instruction of the Hospital dataset. 
When running the code`python apps/train.py --cfg ./config/urbanbis/yingrenshi_large_scene/train_wdepth.yml split demo_overlook ` The program occured an error:`ModuleNotFoundError: No module named 'LoG.dataset.overlook' `
The error occur when using the `dataset.yml` config to load and create the dataset variable, the program try to use the module  LoG.dataset.overlook.OverlookByScale.
Is there missing a file overlook.py in the LoG/dataset/ folder ?

Here is the output log:
```
[Config] merge from parent file: config/urbanbis/yingrenshi_large_scene/dataset.yml
[Config] merge from parent file: config/urbanbis/yingrenshi_large_scene/level_of_gaussian.yml
[Config] merge from parent file: config/urbanbis/yingrenshi_large_scene/stage_8_4.yml
Key is not in the template: split
[Config] replace key $root
[Config] replace key $scale3d
[Config] replace key $root
[Config] replace key $scale3d
[Config] replace key $PLYNAME
[Config] replace key $xyz_scale
[Config] replace key $scale3d
[Config] replace key $PLYNAME
[Config] replace key $xyz_scale
[Config] replace key $max_steps
[Config] replace key $dataset
[Config] replace key $RGB_RENDER_L1_SSIM
[Config] replace key $NAIVE_STAGE
[Config] replace key $val_dataset
Using GPUs: 0
Write to output/urbanbis/yingrenshi_large_scene/log_wdepth_val
Using /home/ubuntu/.cache/torch_extensions/py310_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/ubuntu/.cache/torch_extensions/py310_cu118/compute_radius/build.ninja...
/home/ubuntu/miniconda3/envs/onlyLog/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module compute_radius...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module compute_radius...
[data/Yingrenshi_large_scene/sparse_align/sparse.npz] mean: 0.069, -0.024, 1.299
[data/Yingrenshi_large_scene/sparse_align/sparse.npz] std: 2.941, 3.026, 0.216
[data/Yingrenshi_large_scene/sparse_align/sparse.npz] sigma=1 113698/522154
bounds: [[-2.871, -3.050, 1.083], [3.010, 3.002, 1.515]]
[data/Yingrenshi_large_scene/sparse_align/sparse.npz] sigma=2 473244/522154
bounds: [[-5.812, -6.077, 0.868], [5.951, 6.029, 1.730]]
[data/Yingrenshi_large_scene/sparse_align/sparse.npz] sigma=3 520211/522154
bounds: [[-8.753, -9.103, 0.652], [8.892, 9.055, 1.946]]
[data/Yingrenshi_large_scene/sparse_align/sparse.npz] z_min: 0.349, z_max: 15.085
[Load PLY] load from ply: data/Yingrenshi_large_scene/sparse_align/sparse.npz
[Load PLY] min: [-21.08523507 -25.66368314   0.34905675], max: [ 7.12132441  8.81846224 15.0846947 ]
[Load PLY] scale: 0.0003, 28.8284, mean = 0.0135
[GaussianPoint] scales: [0.0003~0.0135~28.8284]
[GaussianPoint] -> scales: [0.0034~0.0133~0.0540]
Traceback (most recent call last):
  File "/home/ubuntu/repository/Project/sci/LoG/apps/train.py", line 183, in <module>
    main()
  File "/home/ubuntu/repository/Project/sci/LoG/apps/train.py", line 172, in main
    demo(cfg, model, device)
  File "/home/ubuntu/repository/Project/sci/LoG/apps/train.py", line 11, in demo
    dataset = load_object(cfg[cfg.split].dataset.module, cfg[cfg.split].dataset.args)
  File "/home/ubuntu/repository/Project/sci/LoG/LoG/utils/config.py", line 59, in load_object
    module = importlib.import_module(module_path)
  File "/home/ubuntu/miniconda3/envs/onlyLog/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'LoG.dataset.overlook' 
```

Here is my dataset config 
```
 root: data/Yingrenshi_large_scene
PLYNAME: data/Yingrenshi_large_scene/sparse_align/sparse.npz
trainlist: data/Yingrenshi_large_scene/trainlist_20.txt  #currently not randomly choosed
vallist: data/Yingrenshi_large_scene/vallist_20.txt  #currently not randomly choosed thus two currently can be used as the code use list without traverse all filename -|0|-
scale3d: 1.
xyz_scale: 1.
ground_height: &ground_height 1.18

dataset:
  module: LoG.dataset.colmap.ImageDataset
  args:
    root: $root
    namelist:
      - DJI_0200
      - DJI_0201
      - DJI_0202
      - DJI_0203
      - DJI_0204
      - DJI_0205
      - DJI_0206
      - DJI_0207
      - DJI_0208
      - DJI_0209
      - DJI_0210
      - DJI_0211
      - DJI_0212
      - DJI_0213
      - DJI_0214
      - DJI_0215
      - DJI_0216
      - DJI_0217
      - DJI_0218
      - DJI_0219
    cache: cache.pkl
    pre_undis: True
    share_camera: False
    cameras: sparse_align
    scales: [ 4, 8 ]
    crop_size: [ -1, -1 ]
    znear: 0.001
    zfar: 100.
    scale3d: $scale3d
    ext: .JPG
  
val_dataset:
  module: LoG.dataset.colmap.ImageDataset
  args:
    root: $root
    namelist:
      - DJI_0145
      - DJI_0245
      - DJI_0345
      - DJI_0445
      - DJI_0545
      - DJI_0645
      - DJI_0745
      - DJI_0845
      - DJI_0945
      - DJI_0400
      - DJI_0500
      - DJI_0185
      - DJI_0285
      - DJI_0385
      - DJI_0485
      - DJI_0585
      - DJI_0685
      - DJI_0785
      - DJI_0885
      - DJI_0985
    cache: cache_val.pkl
    pre_undis: True
    share_camera: False
    cameras: sparse_align
    scales: [4]
    crop_size: [-1, -1]
    znear: 0.001
    zfar: 100.
    scale3d: $scale3d
    ext: .JPG

overlook:
  iteration:
    init: [0, 1000000, 10000]
  dataset:
    module: LoG.dataset.overlook.OverlookByScale
    args:
      focal: 3000.
      shape: [1920, 1080]
      axis_up: "z"
      ground_height: 2.2
      scales: [1, 8]
      border_length: 25.
      lookat: [0., 0., 0]
      step: 4
      zfar: 200.


demo_interpolate:
  model_state:
    enable_sh: True
    log_query: False
  dataset:
    module: LoG.dataset.demo.InterpolatePath
    args:
      cameras: $PLYNAME
      scale: 4
      steps: 600
      subs:
        - 110MEDIA/- DJI_0001
        - 110MEDIA/- DJI_0333
        - 118MEDIA/- DJI_0666
        - 118MEDIA/- DJI_0999

demo_overlook:
  iteration: 1000
  dataset:
    module: LoG.dataset.overlook.OverlookByScale
    args:
      focal: 3000.
      shape: [1920, 1080]
      axis_up: "z"
      ground_height: *ground_height
      scales: [1, 8]
      border_length: 15.
      lookat: [0., 0., 0]
      step: 10
      zfar: 200.

demo_lookat:
  dataset:
    module: LoG.dataset.overlook.LookAt
    args:
      K: [[1836, 0., 1368],
          [0, 1836, 912],
          [0, 0., 1.]]
      scale: 1
      H: 1824
      W: 2736
      lookat: [0., -1., *ground_height]
      ranges: [[0, 360, 361]]
      radius: [[0.5, 10., 361]]
      angle: 45
  model_state:
    enable_sh: True 
```
